# Generated by Django 5.0.4 on 2024-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cards_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.CharField(default='hearts', max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='value',
            field=models.CharField(default='5', max_length=200),
        ),
    ]
